version: '3.5'

services:

  sidia_db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sidia
    ports:
      - "27016:27017"

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  postgres-data: